vars:
  - config_file: ../config.yaml
  - pipeline_name: pipelineA

stages:
  stage_1:
    cmd: python3 ../src/stage_1.py --config=../config.yaml
    params:
      - ../config.yaml:
          - base
          - stage-1
    deps:
      - ../src/logs.py
    outs:
      - ../output/stage1_output.txt
  stage_2a:
    cmd: python3 ../src/stage_2a.py --config=../config.yaml
    params:
      - ../config.yaml:
          - base
          - stage-2a
    deps:
      - ../src/logs.py
      - ../output/stage1_output.txt
    outs:
      - ../output/stage2a_output.txt
